#!/bin/bash
# Quick deployment script for AAIP data collection automation

set -e  # Exit on error

echo "=================================================="
echo "AAIP Data Collection Automation - Quick Setup"
echo "=================================================="
echo

# Detect init system
if command -v systemctl &> /dev/null; then
    INIT_SYSTEM="systemd"
elif command -v crontab &> /dev/null; then
    INIT_SYSTEM="cron"
else
    echo "❌ Error: Neither systemd nor cron found on this system"
    exit 1
fi

echo "✅ Detected init system: $INIT_SYSTEM"
echo

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

echo "📁 Project paths:"
echo "   Script directory: $SCRIPT_DIR"
echo "   Project root: $PROJECT_ROOT"
echo

# Check Python
if ! command -v python3 &> /dev/null; then
    echo "❌ Error: python3 not found. Please install Python 3.11+"
    exit 1
fi

PYTHON_VERSION=$(python3 --version | cut -d' ' -f2)
echo "✅ Python version: $PYTHON_VERSION"

# Check virtual environment
if [ ! -d "$SCRIPT_DIR/venv" ]; then
    echo "⚠️  Virtual environment not found. Creating one..."
    python3 -m venv "$SCRIPT_DIR/venv"
    source "$SCRIPT_DIR/venv/bin/activate"
    pip install --upgrade pip
    pip install -r "$SCRIPT_DIR/requirements.txt"
    echo "✅ Virtual environment created"
else
    echo "✅ Virtual environment exists"
fi

# Check database connection
echo
echo "🔍 Checking database configuration..."
if [ -f "$SCRIPT_DIR/.env" ]; then
    echo "✅ .env file found"
    source "$SCRIPT_DIR/.env"
    
    if [ -n "$DATABASE_URL" ] || [ -n "$DB_HOST" ]; then
        echo "✅ Database configuration present"
    else
        echo "⚠️  Warning: No database configuration found in .env"
    fi
else
    echo "⚠️  Warning: No .env file found"
    echo "   Please create $SCRIPT_DIR/.env with database credentials"
fi

# Main setup menu
echo
echo "=================================================="
echo "Setup Options:"
echo "=================================================="
echo "1. Install systemd timer (recommended for servers)"
echo "2. Install cron job (alternative)"
echo "3. Test run all collectors manually"
echo "4. Test run single collector"
echo "5. Exit"
echo

read -p "Choose option [1-5]: " choice

case $choice in
    1)
        if [ "$INIT_SYSTEM" != "systemd" ]; then
            echo "❌ systemd not available on this system"
            exit 1
        fi
        
        echo
        echo "📋 Installing systemd timer..."
        
        # Update service file with correct paths
        SERVICE_FILE="/tmp/aaip-scraper.service"
        cp "$PROJECT_ROOT/deployment/aaip-scraper.service" "$SERVICE_FILE"
        
        # Replace placeholders
        sed -i.bak "s|WorkingDirectory=.*|WorkingDirectory=$SCRIPT_DIR|" "$SERVICE_FILE"
        sed -i.bak "s|Environment=\"PATH=.*\"|Environment=\"PATH=$SCRIPT_DIR/venv/bin\"|" "$SERVICE_FILE"
        
        echo "   Service file prepared: $SERVICE_FILE"
        echo
        echo "⚠️  Please review and customize the service file, then run:"
        echo
        echo "   sudo cp $SERVICE_FILE /etc/systemd/system/"
        echo "   sudo cp $PROJECT_ROOT/deployment/aaip-scraper.timer /etc/systemd/system/"
        echo "   sudo systemctl daemon-reload"
        echo "   sudo systemctl enable aaip-scraper.timer"
        echo "   sudo systemctl start aaip-scraper.timer"
        echo "   sudo systemctl status aaip-scraper.timer"
        echo
        ;;
        
    2)
        if [ "$INIT_SYSTEM" != "cron" ] && [ "$INIT_SYSTEM" != "systemd" ]; then
            echo "❌ cron not available on this system"
            exit 1
        fi
        
        echo
        echo "📋 Setting up cron job..."
        
        # Create wrapper script
        WRAPPER="$SCRIPT_DIR/run_collector_cron.sh"
        cat > "$WRAPPER" << EOF
#!/bin/bash
# AAIP Data Collection Cron Wrapper
# Auto-generated by setup_automation.sh

cd "$SCRIPT_DIR"
source venv/bin/activate

# Load environment variables
if [ -f .env ]; then
    export \$(cat .env | grep -v '^#' | xargs)
fi

# Run orchestrator
python3 collect_all_data.py >> /tmp/aaip-collector.log 2>&1
EOF
        chmod +x "$WRAPPER"
        
        echo "✅ Wrapper script created: $WRAPPER"
        echo
        echo "To add to crontab, run:"
        echo
        echo "   crontab -e"
        echo
        echo "Then add this line to run every hour:"
        echo
        echo "   0 * * * * $WRAPPER"
        echo
        echo "To view logs:"
        echo "   tail -f /tmp/aaip-collector.log"
        echo
        ;;
        
    3)
        echo
        echo "🚀 Running all collectors..."
        cd "$SCRIPT_DIR"
        source venv/bin/activate
        
        # Load environment
        if [ -f .env ]; then
            export $(cat .env | grep -v '^#' | xargs)
        fi
        
        python3 collect_all_data.py
        ;;
        
    4)
        echo
        echo "Available collectors:"
        echo "1. scraper.py - Main AAIP processing & draws"
        echo "2. aaip_news_scraper.py - News updates"
        echo "3. express_entry_collector.py - Express Entry data"
        echo "4. alberta_economy_collector.py - Economy indicators"
        echo "5. quarterly_labor_market_collector.py - Labor market"
        echo "6. job_bank_scraper.py - Job postings"
        echo "7. trend_analysis_engine.py - Trend analysis"
        echo
        read -p "Choose collector [1-7]: " collector_choice
        
        case $collector_choice in
            1) SCRIPT="scraper.py" ;;
            2) SCRIPT="aaip_news_scraper.py" ;;
            3) SCRIPT="express_entry_collector.py" ;;
            4) SCRIPT="alberta_economy_collector.py" ;;
            5) SCRIPT="quarterly_labor_market_collector.py" ;;
            6) SCRIPT="job_bank_scraper.py" ;;
            7) SCRIPT="trend_analysis_engine.py" ;;
            *) echo "Invalid choice"; exit 1 ;;
        esac
        
        echo
        echo "🚀 Running $SCRIPT..."
        cd "$SCRIPT_DIR"
        source venv/bin/activate
        
        # Load environment
        if [ -f .env ]; then
            export $(cat .env | grep -v '^#' | xargs)
        fi
        
        python3 "$SCRIPT"
        ;;
        
    5)
        echo "Exiting..."
        exit 0
        ;;
        
    *)
        echo "❌ Invalid choice"
        exit 1
        ;;
esac

echo
echo "=================================================="
echo "✅ Setup complete!"
echo "=================================================="
